---
title: Friends of Pheasant Branch Conservancy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: http://friendsofpheasantbranch.org
prose:
  rooturl: _posts
  ignore:
  - _config.yml
  - index.html
  - "/_includes"
  - "/_layouts"
  - "/_sass"
  metadata:
    _posts:
    - name: published
      field:
        element: hidden
        value: true
    - name: layout
      field:
        element: hidden
        value: post
    - name: category
      field:
        element: multiselect
        label: Add Category
        placeholder: Select a Category
        options:
        - name: Restore
          value: restore
        - name: Education
          value: education
        - name: Watershed
          value: watershed
markdown: kramdown
