# Site settings
title:                Friends of Pheasant Branch Conservancy
email:                michael@michaelfreiman.com
description:          UI Components created by Michael Freiman

baseurl: "/pheasantbranch" # the subpath of your site, e.g. /blog
url: "http://friends-of-pheasant-branch.github.io/pheasantbranch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
collections:
  tables:
    output: true
  tabs:
    output: true
